// ---- THE LONG WINTER (rooms 41-75) --------------------------------------------------------------------------------
const ICY = (n, name, boss, rows) => ({ name: `${n} - The Frozen Elder: ${name}`, exit: 'right', boss: { icy: true, ...boss }, rows });
const CYCLONE = (n, name, boss, rows) => ({ name: `${n} - The Cyclone: ${name}`, exit: 'right', boss: { cyclone: true, ...boss }, rows });

LEVELS.push(
  { name: '41 - The Long Winter: Thaw', exit: 'right',
    rows: RUN([['f', 3], ['pit', 4], ['f', 3], ['drift', 4], ['f', 3], ['pop', 1], ['f', 3], ['pit', 5, 'W'], ['f', 3]]) },
  { name: '42 - The Long Winter: Hollow Drifts', exit: 'right',
    rows: RUN([['f', 2], ['tun', 5], ['f', 3], ['pit', 4], ['f', 3], ['pop', 1], ['f', 2], ['drift', 5], ['f', 3]]) },
  { name: '43 - The Long Winter: Wide Open', exit: 'right',
    rows: RUN([['f', 3], ['big', 8], ['f', 3], ['pit', 5, 'W'], ['f', 3], ['tun', 4], ['f', 3], ['pop', 1]]) },
  { name: '44 - The Long Winter: White Steps', exit: 'right',
    rows: RUN([['f', 3], ['pit', 6], ['f', 2], ['drift', 6], ['f', 2], ['pit', 6, 'W'], ['f', 2], ['tun', 5], ['f', 3]]) },
  { name: '45 - The Long Winter: Snapping Snow', exit: 'right',
    rows: RUN([['f', 3], ['pop', 2], ['f', 2], ['pit', 5], ['f', 3], ['drift', 5], ['f', 3]]) },
  { name: '46 - The Long Winter: Two Chasms', exit: 'right',
    rows: RUN([['f', 2], ['big', 9], ['f', 3], ['big', 9], ['f', 3], ['pit', 4, 'W'], ['f', 3]]) },
  { name: '47 - The Long Winter: Double Tunnel', exit: 'right',
    rows: RUN([['f', 2], ['tun', 5], ['f', 2], ['tun', 5], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['drift', 5], ['f', 3], ['pit', 4], ['f', 2]]) },
  { name: '48 - The Long Winter: Hurdles', exit: 'right',
    rows: RUN([['f', 2], ['hur', 2], ['f', 3], ['pit', 4], ['f', 2], ['hur', 2], ['f', 3], ['pop', 1], ['f', 3], ['pit', 5, 'W'], ['f', 3]]) },
  { name: '49 - The Long Winter: Pop and Drift', exit: 'right',
    rows: RUN([['f', 2], ['pop', 1], ['f', 2], ['drift', 4], ['f', 2], ['pop', 2], ['f', 2], ['pit', 4]]) },
  { name: '50 - The Long Winter: Frozen Wall II', exit: 'top', rows: CLIMB_WALL({ curtain: true, drift: true }) },
  { name: '51 - The Long Winter: Wide and Cold', exit: 'right',
    rows: RUN([['f', 3], ['big', 10], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['pop', 1], ['f', 2], ['drift', 5], ['f', 2]]) },
  { name: '52 - The Long Winter: Frozen Steps', exit: 'right',
    rows: RUN([['f', 2], ['pit', 5], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['pit', 5], ['f', 2], ['tun', 5], ['f', 2], ['drift', 5], ['f', 2]]) },
  { name: '53 - The Long Winter: Blink and Crawl', exit: 'right',
    rows: RUN([['f', 2], ['pop', 1], ['f', 2], ['tun', 5], ['f', 2], ['pop', 1], ['f', 2], ['drift', 5], ['f', 2]]) },
  { name: '54 - The Long Winter: Crystal Fields', exit: 'right',
    rows: RUN([['f', 2], ['big', 8], ['f', 2], ['big', 8, 'W'], ['f', 2], ['big', 8], ['f', 2]]) },
  { name: '55 - The Long Winter: Rising Blizzard', exit: 'top', rise: { speed: 5, delay: 3 }, rows: CLIMB_POP() },
  { name: '56 - The Long Winter: Sharp Edges', exit: 'right',
    rows: RUN([['f', 2], ['hur', 2], ['f', 2], ['drift', 4], ['f', 2], ['hur', 2], ['f', 2], ['pit', 6], ['f', 2], ['pop', 1], ['f', 2]]) },
  { name: '57 - The Long Winter: Snowed Under', exit: 'right',
    rows: RUN([['f', 2], ['pit', 6, 'W'], ['f', 2], ['tun', 5], ['f', 2], ['big', 8], ['f', 2], ['pop', 1], ['f', 2]]) },
  { name: '58 - The Long Winter: Pillars in the White', exit: 'right',
    rows: RUN([['f', 2], ['pop', 1], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['pop', 1], ['f', 2], ['pit', 5], ['f', 2]]) },
  { name: '59 - The Long Winter: Everything at Once', exit: 'right',
    rows: RUN([['f', 2], ['tun', 4], ['f', 2], ['pop', 1], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['big', 8], ['f', 2]]) },
  { name: '60 - The Long Winter: Rising Powder II', exit: 'top', rise: { speed: 10, delay: 1.5 },
    rows: CLIMB_LADDER([[15, 19, 22], [9, 17, 20], [6, 9, 12], [12, 27, 30]]) },
  { name: '61 - The Long Winter: Hollow Hurdles', exit: 'right',
    rows: RUN([['f', 2], ['hur', 2], ['f', 2], ['tun', 5], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['pop', 1], ['f', 2], ['hur', 2]]) },
  { name: '62 - The Long Winter: Ash and Ice', exit: 'right',
    rows: RUN([['f', 2], ['big', 9, 'W'], ['f', 2], ['drift', 5], ['f', 2], ['big', 9], ['f', 2], ['pop', 1]]) },
  { name: '63 - The Long Winter: Frostbitten', exit: 'right',
    rows: RUN([['f', 2], ['tun', 5], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['tun', 5], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['pop', 1]]) },
  { name: '64 - The Long Winter: The Last Field', exit: 'right',
    rows: RUN([['f', 2], ['pop', 1], ['f', 2], ['big', 8, 'W'], ['f', 2], ['tun', 4], ['f', 2], ['pit', 5], ['f', 2]]) },
  { name: '65 - The Long Winter: Frozen Wall III', exit: 'top', rise: { speed: 6, delay: 2 }, rows: CLIMB_WALL({ curtain: true, drift: true }) },

  // ---- THE FROZEN ELDER (rooms 66-75): the elder goat is back with icicles all over its horns. Besides its usual spikes
  // it launches icicles straight at you (icicleEvery - the horns glint first), see Boss.js.
  // boss: { icy: true, speed, startX, firstDelay, spikeEvery, icicleEvery, cornerX (final room) }
  ICY(66, 'It Wakes', { speed: 19, startX: -90, firstDelay: 3, icicleEvery: 5 },
    RUN([['f', 2], ['pit', 4], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5, 'W'], ['f', 3], ['hur', 2], ['f', 4]])),
  ICY(67, 'Frost Steps', { speed: 20, startX: -88, firstDelay: 3, icicleEvery: 4.6, spikeEvery: 6 },
    RUN([['f', 2], ['hur', 2], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5], ['f', 2], ['drift', 3], ['f', 2], ['pit', 4, 'W'], ['f', 2], ['hur', 2], ['f', 3]])),
  ICY(68, 'Glacier Chasm', { speed: 21, startX: -86, firstDelay: 2.5, icicleEvery: 4.4, spikeEvery: 5.5 },
    RUN([['f', 2], ['big', 8], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5, 'W'], ['f', 2], ['big', 8], ['f', 2]])),
  ICY(69, 'Thin Air', { speed: 22, startX: -84, firstDelay: 2.5, icicleEvery: 4.2, spikeEvery: 5 },
    RUN([['f', 2], ['pit', 5], ['f', 2], ['pop', 1], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['drift', 3], ['f', 2]])),
  ICY(70, 'Hail of Ice', { speed: 23, startX: -82, firstDelay: 2.5, icicleEvery: 3.8, spikeEvery: 5 },
    RUN([['f', 2], ['drift', 4], ['f', 2], ['pit', 6], ['f', 2], ['hur', 2], ['f', 2], ['big', 8], ['f', 2], ['hur', 2], ['f', 2]])),
  ICY(71, 'Frozen Horns', { speed: 24, startX: -80, firstDelay: 2, icicleEvery: 3.6, spikeEvery: 4.6 },
    RUN([['f', 2], ['pit', 5, 'W'], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['hur', 2], ['f', 2]])),
  ICY(72, 'Hollow Run', { speed: 25, startX: -78, firstDelay: 2, icicleEvery: 3.4, spikeEvery: 4.4, ceiling: true },
    RUN([['f', 2], ['big', 9], ['f', 2], ['pop', 1], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['drift', 3], ['f', 2], ['hur', 2], ['f', 2]])),
  ICY(73, 'The Long Shadow', { speed: 26, startX: -76, firstDelay: 2, icicleEvery: 3.2, spikeEvery: 4.2, ceiling: true },
    RUN([['f', 2], ['hur', 2], ['f', 2], ['pit', 6], ['f', 2], ['hur', 2], ['f', 2], ['big', 8, 'W'], ['f', 2], ['pit', 5], ['f', 2]])),
  ICY(74, 'Last Breath', { speed: 27, startX: -74, firstDelay: 2, icicleEvery: 3, spikeEvery: 4, ceiling: true },
    RUN([['f', 2], ['pit', 5], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['hur', 2], ['f', 2], ['big', 8], ['f', 2], ['hur', 2]])),
  // the last room: flat floor, and the exit is sealed. The goat drives you into the right-hand corner (its snout stops at
  // cornerX) and hurls one huge homing icicle. Without a Tough Hide it kills you; with one it glances off, pierces the
  // goat's leg and the goat runs away - dropping goat horns. The exit opens once you pick them up.
  ICY(75, 'Cornered', { speed: 24, startX: -80, firstDelay: 2, icicleEvery: 3.5, cornerX: 236 },
    RUN([['f', 34]], g => { g.put(17, 26, 'S'); })),
  // ---- THE STORMLANDS (rooms 76-100): no bosses, just wind and wreckage - and in the last 10, tornadoes ('T') that
  // hurl bricks at you every 5 seconds (GameScene.updateTornadoes). The first brick to ever clip you in a room just
  // stuns you for 2 seconds; every one after costs a life, same as any other hazard. ---------------------------------
  { name: '76 - Stormlands: First Gale', exit: 'right',
    rows: RUN([['f', 3], ['pit', 4], ['f', 3], ['hur', 2], ['f', 3], ['drift', 4], ['f', 3], ['pit', 5, 'W'], ['f', 3]]) },
  { name: '77 - Stormlands: Windswept Ledge', exit: 'right',
    rows: RUN([['f', 2], ['pop', 1], ['f', 2], ['pit', 5], ['f', 2], ['tun', 5], ['f', 2], ['drift', 4], ['f', 2]]) },
  { name: '78 - Stormlands: Loose Scree', exit: 'right',
    rows: RUN([['f', 2], ['hur', 2], ['f', 2], ['hur', 2], ['f', 2], ['pit', 6, 'W'], ['f', 2], ['pop', 1], ['f', 2], ['pit', 4], ['f', 2]]) },
  { name: '79 - Stormlands: Gale Steps', exit: 'right',
    rows: RUN([['f', 2], ['pit', 5], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5], ['f', 2], ['drift', 4], ['f', 2]]) },
  { name: '80 - Stormlands: Crosswind Chasm', exit: 'right',
    rows: RUN([['f', 2], ['big', 9], ['f', 3], ['big', 9, 'W'], ['f', 3], ['pop', 1], ['f', 3]]) },
  { name: '81 - Stormlands: Rimewind Wall', exit: 'top', rows: CLIMB_WALL({ drift: true }) },
  { name: '82 - Stormlands: Thunderhead', exit: 'right',
    rows: RUN([['f', 2], ['drift', 5], ['f', 2], ['pit', 5], ['f', 2], ['tun', 5], ['f', 2], ['pit', 4, 'W'], ['f', 2], ['hur', 2], ['f', 2]]) },
  { name: '83 - Stormlands: Squall Line', exit: 'right',
    rows: RUN([['f', 2], ['hur', 2], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['hur', 2], ['f', 2], ['big', 8], ['f', 2], ['pop', 1], ['f', 2]]) },
  { name: '84 - Stormlands: Broken Scaffold', exit: 'right',
    rows: RUN([['f', 2], ['pop', 2], ['f', 2], ['pit', 5], ['f', 2], ['hur', 2], ['f', 2], ['drift', 5], ['f', 2]]) },
  { name: '85 - Stormlands: Hollow Gust', exit: 'right',
    rows: RUN([['f', 2], ['tun', 5], ['f', 2], ['tun', 5], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['drift', 4], ['f', 2], ['pit', 4], ['f', 2]]) },
  { name: '86 - Stormlands: Rising Squall', exit: 'top', rise: { speed: 6, delay: 2 }, rows: CLIMB_POP() },
  { name: '87 - Stormlands: Storm Cellar', exit: 'right',
    rows: RUN([['f', 2], ['pit', 6], ['f', 2], ['tun', 5], ['f', 2], ['pop', 1], ['f', 2], ['pit', 5, 'W'], ['f', 2]]) },
  { name: '88 - Stormlands: Shattered Steps', exit: 'right',
    rows: RUN([['f', 2], ['hur', 2], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5, 'W'], ['f', 5]]) },
  { name: '89 - Stormlands: Ladder in the Wind', exit: 'top', rise: { speed: 8, delay: 2 },
    rows: CLIMB_LADDER([[16, 9, 12], [12, 17, 20], [8, 25, 28], [4, 12, 15]]) },
  { name: '90 - Stormlands: The Lull Before', exit: 'right',
    rows: RUN([['f', 5], ['pit', 4], ['f', 5], ['drift', 4], ['f', 5], ['pop', 1], ['f', 5]]) },

  // the last 10 Stormlands rooms: little tornadoes ('T') stand in the open and hurl bricks at you every 5 seconds
  { name: '91 - Stormlands: Tornado Alley', exit: 'right',
    rows: RUN([['f', 5], ['pit', 5], ['f', 5], ['hur', 2], ['f', 5], ['pit', 5, 'W'], ['f', 5]], g => { g.put(17, 15, 'T'); }) },
  { name: '92 - Stormlands: Funnel Steps', exit: 'right',
    rows: RUN([['f', 3], ['hur', 2], ['f', 3], ['pit', 5], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5, 'W'], ['f', 3]], g => { g.put(17, 17, 'T'); }) },
  { name: '93 - Stormlands: Debris Field', exit: 'right',
    rows: RUN([['f', 4], ['big', 8], ['f', 4], ['pit', 5], ['f', 4], ['big', 8, 'W'], ['f', 4]],
      g => { g.put(17, 16, 'T'); g.put(17, 37, 'T'); }) },
  { name: '94 - Stormlands: Twin Funnels', exit: 'right',
    rows: RUN([['f', 3], ['pit', 5], ['f', 3], ['pit', 5, 'W'], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5], ['f', 3]],
      g => { g.put(17, 12, 'T'); g.put(17, 25, 'T'); }) },
  { name: '95 - Stormlands: Windbreak Wall', exit: 'top',
    rows: B(g => {
      g.fill(22, 22, 0, 39, '#'); g.put(21, 2, 'P');
      g.fill(9, 21, 20, 21, '#');                                          // wall to climb
      g.put(19, 6, '####'); g.put(18, 7, 'S');
      g.put(16, 12, '####'); g.put(15, 13, 'T');                           // a tornado waits on this ledge
      g.put(8, 22, 'D'); g.put(6, 24, '######'); g.put(5, 26, 'S');
    }) },
  { name: '96 - Stormlands: Rubble Run', exit: 'right',
    rows: RUN([['f', 3], ['pop', 1], ['f', 3], ['pit', 5], ['f', 3], ['pop', 1], ['f', 3], ['pit', 5, 'W'], ['f', 3]], g => { g.put(17, 13, 'T'); }) },
  { name: '97 - Stormlands: The Vortex Gap', exit: 'right',
    rows: RUN([['f', 3], ['big', 9], ['f', 3], ['big', 9, 'W'], ['f', 3], ['pit', 4], ['f', 3]],
      g => { g.put(17, 16, 'T'); g.put(17, 35, 'T'); }) },
  { name: "98 - Stormlands: Storm's Edge", exit: 'right',
    rows: RUN([['f', 2], ['pit', 5, 'W'], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5], ['f', 2], ['hur', 2], ['f', 2], ['big', 8], ['f', 2]],
      g => { g.put(17, 10, 'T'); g.put(17, 35, 'T'); }) },
  { name: '99 - Stormlands: Maelstrom', exit: 'right',
    rows: RUN([['f', 2], ['pit', 5], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['big', 8], ['f', 2], ['pit', 5], ['f', 2]],
      g => { g.put(17, 10, 'T'); g.put(17, 17, 'T'); g.put(17, 27, 'T'); }) },
  { name: '100 - Stormlands: Eye of the Storm', exit: 'right',
    rows: RUN([['f', 34]], g => { g.put(17, 6, 'T'); g.put(17, 14, 'T'); g.put(17, 26, 'T'); g.put(17, 34, 'T'); g.put(17, 20, 'S'); }) },

  // ---- THE CYCLONE (rooms 101-120): a giant tornado chases you, dropping a small tornado just ahead of you every 2-5
  // seconds (and, from room 106, dust devils that race along the floor). Small tornado touches: stun, then knockback,
  // then it flings you into the Cyclone. Room 120: the gale pins you in the corner - then the wind stops, the Cyclone
  // dies out and Jeff sets up shop (V to trade); the exit leads on into the Wreckage. See Cyclone.js.
  CYCLONE(101, 'First Winds', { speed: 26, startX: -100, firstDelay: 3 },
    RUN([['f', 4], ['pit', 4], ['f', 5], ['hur', 2], ['f', 5], ['pit', 5], ['f', 6]])),
  CYCLONE(102, 'Funnel Chase', { speed: 27, startX: -98 },
    RUN([['f', 3], ['hur', 2], ['f', 4], ['pit', 5], ['f', 4], ['hur', 2], ['f', 4], ['pit', 4], ['f', 4]])),
  CYCLONE(103, 'Swept Away', { speed: 28, startX: -96 },
    RUN([['f', 3], ['big', 8], ['f', 4], ['pit', 5], ['f', 4], ['hur', 2], ['f', 5]])),
  CYCLONE(104, 'Debris Rain', { speed: 29, startX: -94 },
    RUN([['f', 3], ['pit', 5, 'W'], ['f', 4], ['hur', 2], ['f', 4], ['pit', 5], ['f', 4], ['drift', 3], ['f', 3]])),
  CYCLONE(105, 'Gale Force', { speed: 30, startX: -92 },
    RUN([['f', 3], ['big', 8], ['f', 3], ['big', 8], ['f', 4], ['hur', 2], ['f', 3]])),
  CYCLONE(106, 'Dust Devils', { speed: 30, startX: -92, runnerEvery: 7 },
    RUN([['f', 4], ['pit', 4], ['f', 5], ['pit', 5], ['f', 5], ['hur', 2], ['f', 5]])),
  CYCLONE(107, 'Spiral Steps', { speed: 31, startX: -90, runnerEvery: 6.5 },
    RUN([['f', 3], ['hur', 2], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5], ['f', 3], ['hur', 2], ['f', 3], ['pit', 4], ['f', 3]])),
  CYCLONE(108, "The Twister's Wake", { speed: 32, startX: -90, runnerEvery: 6.5 },
    RUN([['f', 3], ['pit', 5, 'W'], ['f', 3], ['big', 8], ['f', 3], ['pit', 5], ['f', 4]])),
  CYCLONE(109, 'Whirlwind Gap', { speed: 32, startX: -88, runnerEvery: 6 },
    RUN([['f', 3], ['big', 9], ['f', 4], ['big', 9], ['f', 4], ['hur', 2], ['f', 3]])),
  CYCLONE(110, 'Eye Wall', { speed: 33, startX: -88, runnerEvery: 6 },
    RUN([['f', 3], ['pop', 1], ['f', 3], ['pit', 5], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5], ['f', 3]])),
  CYCLONE(111, 'Uprooted', { speed: 34, startX: -86, runnerEvery: 5.5 },
    RUN([['f', 3], ['hur', 2], ['f', 3], ['pit', 5, 'W'], ['f', 3], ['hur', 2], ['f', 3], ['big', 8], ['f', 3]])),
  CYCLONE(112, 'Storm Surge', { speed: 34, startX: -86, runnerEvery: 5.5 },
    RUN([['f', 3], ['pit', 5], ['f', 3], ['pit', 5], ['f', 3], ['pit', 5], ['f', 3], ['drift', 3], ['f', 3]])),
  CYCLONE(113, 'Flying Rubble', { speed: 35, startX: -84, runnerEvery: 5 },
    RUN([['f', 3], ['big', 8], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5, 'W'], ['f', 3], ['hur', 2], ['f', 3]])),
  CYCLONE(114, 'Vortex Run', { speed: 36, startX: -84, runnerEvery: 5 },
    RUN([['f', 3], ['pop', 1], ['f', 3], ['big', 8], ['f', 3], ['pit', 5], ['f', 4]])),
  CYCLONE(115, 'Screaming Wind', { speed: 36, startX: -82, runnerEvery: 4.5 },
    RUN([['f', 3], ['hur', 2], ['f', 2], ['pit', 5], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['hur', 2], ['f', 3]])),
  CYCLONE(116, 'Torn Earth', { speed: 37, startX: -82, runnerEvery: 4.5 },
    RUN([['f', 3], ['big', 9], ['f', 3], ['pit', 5], ['f', 3], ['big', 8], ['f', 3]])),
  CYCLONE(117, 'The Long Gust', { speed: 38, startX: -80, runnerEvery: 4.5 },
    RUN([['f', 3], ['pit', 5], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5, 'W'], ['f', 3], ['pop', 1], ['f', 3]])),
  CYCLONE(118, 'Heart of the Storm', { speed: 39, startX: -80, runnerEvery: 4 },
    RUN([['f', 3], ['big', 8], ['f', 3], ['big', 8, 'W'], ['f', 3], ['hur', 2], ['f', 3], ['pit', 4]])),
  CYCLONE(119, 'Last Gale', { speed: 40, startX: -78, runnerEvery: 4 },
    RUN([['f', 3], ['hur', 2], ['f', 3], ['pit', 5], ['f', 3], ['big', 8], ['f', 3], ['hur', 2], ['f', 3], ['pit', 4]])),
  // the last room: flat floor, sealed exit. After finalStand seconds the gale pins you in the right-hand corner and the
  // Cyclone closes in - then the wind stops dead, the Cyclone dies out, the exit opens and Jeff sets up his stall.
  CYCLONE(120, 'Cornered', { speed: 32, startX: -90, runnerEvery: 5, finalStand: 7 },
    RUN([['f', 34]], g => { g.put(17, 22, 'S'); g.put(17, 30, 'S'); })),
);
