// ---- THE WRECKAGE (rooms 121-150): what the Cyclone left behind. No boss, but small tornadoes still whirl up ahead of
// you (winds: see Gusts.js) - and from room 126, dust devils roll in from the left - while Stormlands tornadoes ('T')
// hurl bricks. Small tornado touches: stun, then knockback, then you're flung into the ceiling and buried in rubble.
// withT(rows, [[row, col], ...]) drops brick-throwing tornadoes into a prebuilt layout (the climbs).
const withT = (rows, spots) => rows.map((s, r) => spots.reduce((line, [tr, c]) => tr === r ? line.slice(0, c) + 'T' + line.slice(c + 1) : line, s));
const WRECK = (n, name, winds, rows, extra = {}) => ({ name: `${n} - The Wreckage: ${name}`, exit: 'right', winds, rows, ...extra });
const tAt = (...cols) => g => cols.forEach(c => g.put(17, c, 'T'));

LEVELS.push(
  WRECK(121, 'Aftermath', { every: [4, 6], firstDelay: 3 },
    RUN([['f', 4], ['pit', 4], ['f', 5], ['hur', 2], ['f', 5], ['pit', 5], ['f', 6]])),
  WRECK(122, 'Loose Shingles', { every: [3.5, 5.5] },
    RUN([['f', 3], ['hur', 2], ['f', 4], ['pit', 5], ['f', 4], ['hur', 2], ['f', 4], ['pit', 4], ['f', 4]])),
  WRECK(123, 'Thrown Bricks', { every: [3.5, 5.5] },
    RUN([['f', 4], ['pit', 5], ['f', 5], ['hur', 2], ['f', 5], ['pit', 5], ['f', 5]], tAt(16))),
  WRECK(124, 'Fallen Rafters', { every: [3.5, 5] },
    RUN([['f', 3], ['big', 8], ['f', 4], ['pit', 5], ['f', 4], ['hur', 2], ['f', 5]], tAt(30))),
  WRECK(125, 'Splintered Wall', { every: [3.5, 5] },
    withT(CLIMB_WALL(), [[15, 13], [21, 30]]), { exit: 'top' }),
  WRECK(126, 'Dust Devils Return', { every: [3.5, 5], runnerEvery: 7 },
    RUN([['f', 4], ['pit', 4], ['f', 5], ['pit', 5], ['f', 5], ['hur', 2], ['f', 5]], tAt(20))),
  WRECK(127, 'Rubble Steps', { every: [3.5, 5], runnerEvery: 6.5 },
    RUN([['f', 3], ['hur', 2], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5], ['f', 3], ['hur', 2], ['f', 3], ['pit', 4], ['f', 3]], tAt(12))),
  WRECK(128, 'Broken Bridge', { every: [3.2, 5], runnerEvery: 6.5 },
    RUN([['f', 3], ['big', 9], ['f', 4], ['big', 9], ['f', 4], ['hur', 2], ['f', 3]], tAt(8, 30))),
  WRECK(129, 'Debris Drift', { every: [3, 4.5], runnerEvery: 6 },
    RUN([['f', 3], ['pit', 5, 'W'], ['f', 3], ['drift', 4], ['f', 3], ['pit', 5], ['f', 3], ['hur', 2], ['f', 3]], tAt(14))),
  WRECK(130, 'Collapsed Tower', { every: [3, 5] },
    withT(CLIMB_POP(), [[17, 13], [20, 30]]), { exit: 'top', rise: { speed: 6, delay: 3 } }),
  WRECK(131, 'Two Throwers', { every: [3, 4.5], runnerEvery: 6 },
    RUN([['f', 3], ['pit', 5], ['f', 3], ['pit', 5, 'W'], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5], ['f', 3]], tAt(10, 26))),
  WRECK(132, 'Scattered Roof', { every: [3, 4.5], runnerEvery: 5.5 },
    RUN([['f', 3], ['pop', 1], ['f', 3], ['pit', 5], ['f', 3], ['pop', 1], ['f', 3], ['pit', 5, 'W'], ['f', 3]], tAt(14))),
  WRECK(133, 'Hollow House', { every: [3, 4.5], runnerEvery: 5.5 },
    RUN([['f', 2], ['tun', 5], ['f', 3], ['pit', 5], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5, 'W'], ['f', 3]], tAt(28))),
  WRECK(134, 'Splinter Run', { every: [3, 4.5], runnerEvery: 5 },
    RUN([['f', 3], ['hur', 2], ['f', 2], ['pit', 5], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['hur', 2], ['f', 3]], tAt(9, 24))),
  WRECK(135, 'Wind Ladder', { every: [3, 5] },
    withT(CLIMB_LADDER([[16, 19, 22], [10, 17, 20]]), [[12, 28], [21, 35]]), { exit: 'top', rise: { speed: 8, delay: 2.5 } }),
  WRECK(136, 'Shattered Glass', { every: [2.8, 4.5], runnerEvery: 5 },
    RUN([['f', 3], ['big', 8], ['f', 3], ['pit', 5], ['f', 3], ['big', 8, 'W'], ['f', 3]], tAt(6, 30))),
  WRECK(137, 'Whirling Wreck', { every: [2.8, 4.2], runnerEvery: 5 },
    RUN([['f', 3], ['pit', 5], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5, 'W'], ['f', 3], ['pop', 1], ['f', 3]], tAt(18))),
  WRECK(138, 'Brick Storm', { every: [3, 4.5], runnerEvery: 6 },
    RUN([['f', 5], ['pit', 5], ['f', 5], ['hur', 2], ['f', 5], ['pit', 5, 'W'], ['f', 5]], tAt(8, 20, 32))),
  WRECK(139, 'Torn Floorboards', { every: [2.8, 4.2], runnerEvery: 4.5 },
    RUN([['f', 2], ['pit', 5], ['f', 2], ['pit', 5], ['f', 2], ['pit', 5], ['f', 2], ['drift', 3], ['f', 3]], tAt(22))),
  WRECK(140, 'Rubble Wall', { every: [3, 4.5] },
    withT(CLIMB_POP(), [[17, 13], [20, 30]]), { exit: 'top', rise: { speed: 7, delay: 2 } }),
  WRECK(141, 'Gale Gauntlet', { every: [2.6, 4], runnerEvery: 4.5 },
    RUN([['f', 3], ['hur', 2], ['f', 3], ['big', 8], ['f', 3], ['hur', 2], ['f', 3], ['pit', 5, 'W'], ['f', 3]], tAt(10, 34))),
  WRECK(142, 'The Leaning House', { every: [2.6, 4], runnerEvery: 4.5 },
    RUN([['f', 2], ['tun', 5], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['tun', 5], ['f', 2], ['pit', 5], ['f', 2], ['pop', 1]], tAt(25))),
  WRECK(143, 'Flying Timber', { every: [2.5, 4], runnerEvery: 4 },
    RUN([['f', 3], ['pit', 5], ['f', 3], ['hur', 2], ['f', 3], ['big', 8], ['f', 3], ['hur', 2], ['f', 3]], tAt(12, 28))),
  WRECK(144, 'Ruined Mill', { every: [2.5, 4], runnerEvery: 4 },
    RUN([['f', 3], ['pop', 1], ['f', 3], ['big', 9], ['f', 3], ['pit', 5, 'W'], ['f', 3]], tAt(8, 22, 36))),
  WRECK(145, 'The Long Climb Out', { every: [2.6, 4] },
    withT(CLIMB_WALL({ drift: true }), [[15, 13], [21, 30]]), { exit: 'top', rise: { speed: 9, delay: 2 } }),
  WRECK(146, "Wreckers' Row", { every: [2.4, 3.8], runnerEvery: 4 },
    RUN([['f', 2], ['hur', 2], ['f', 2], ['pit', 5], ['f', 2], ['hur', 2], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['hur', 2], ['f', 2], ['pit', 4], ['f', 2]], tAt(10, 24, 36))),
  WRECK(147, 'Bricks and Breeze', { every: [2.4, 3.6], runnerEvery: 3.8 },
    RUN([['f', 3], ['big', 8], ['f', 3], ['big', 8, 'W'], ['f', 3], ['hur', 2], ['f', 3]], tAt(6, 18, 30))),
  WRECK(148, 'Storm Debris', { every: [2.2, 3.5], runnerEvery: 3.5 },
    RUN([['f', 2], ['pit', 5], ['f', 2], ['pop', 1], ['f', 2], ['pit', 5, 'W'], ['f', 2], ['big', 8], ['f', 2]], tAt(9, 20, 34))),
  WRECK(149, 'The Last Ruin', { every: [2.2, 3.4], runnerEvery: 3.5 },
    RUN([['f', 3], ['hur', 2], ['f', 3], ['pit', 5], ['f', 3], ['big', 8], ['f', 3], ['hur', 2], ['f', 3], ['pit', 4]], tAt(8, 18, 28, 38))),
  // the last room: a flat floor, five brick throwers and the wind at its worst. The exit is the end of the game.
  WRECK(150, 'Final Gust', { every: [2, 3], runnerEvery: 3 },
    RUN([['f', 34]], g => { tAt(6, 14, 22, 30, 37)(g); g.put(14, 18, 'S'); g.put(14, 26, 'S'); })),
);
